# Azure DevOps YAML Pipeline from Bow Data Toolkits

trigger:
    branches:
        include:
            - "*"

resources:
    repositories:
        - repository: bowdata-toolkits
          type: git
          name: toolkits/bowdata.toolkits.azure-pipelines
          ref: refs/heads/master

parameters:
  - name: workingDirectory
    default: $(Build.SourcesDirectory)
  - name: preRelease
    default: "a"
  - name: logLevel
    default: DEBUG
    type: string
    displayName: "Log Level"
    values:
      - DEBUG
      - INFO
      - WARNING
      - ERROR
      - CRITICAL

stages:
  - template: /python/pipelines/package-pipeline.yaml@bowdata-toolkits
    parameters:
      preRelease: ${{parameters.preRelease}}
      logLevel: ${{parameters.logLevel}}
      workingDirectory: ${{parameters.workingDirectory}}
