# Azure DevOps YAML Pipeline from Bow Data Toolkits

trigger:
    branches:
        include:
            - "*"

resources:
    repositories:
        - repository: bowdata-toolkits
          type: git
          name: toolkits/bowdata.toolkits.azure-pipelines
          ref: refs/heads/master

parameters:
  - name: workingDirectory
    default: $(Build.SourcesDirectory)
  - name: preRelease
    default: "-a"
  - name: logLevel
    default: DEBUG
    type: string
    displayName: "Log Level"
    values:
      - DEBUG
      - INFO
      - WARNING
      - ERROR
      - CRITICAL
  - name: azureDockerStageCondition
    default: succeeded()
  - name: azureDockerStageDependsOn
    type: object
    default: [Build]
# Parameter Sets
  - name: _ignore_params
    type: object
    default: []
  - name: _general_params
    type: object
    default:
      - logLevel
      - workingDirectory
  - name: _azure_docker_stage_params
    type: object
    default:
      - azureDockerStageCondition
      - azureDockerStageDependsOn
      - dockerhubServiceConnection
      - containerPort
      - hostPort
      - containerRuntimeVariables
      - dockerhubAccount

stages:
  - template: /python/pipelines/package-pipeline.yaml@bowdata-toolkits
    parameters:
      preRelease: ${{parameters.preRelease}}
      logLevel: ${{parameters.logLevel}}
      workingDirectory: ${{parameters.workingDirectory}}
      integrationTestStages:
        # docker image build, test & push stage on Azure agent
        - template: /containers/stages/azure-docker-stage.yaml
          parameters:
            ${{ each pair in parameters }}:
              ${{if and(or(containsValue(parameters._azure_docker_stage_params, pair.key), containsValue(parameters._general_params, pair.key)), not(containsValue(parameters._ignore_params, pair.key)))}}:
                ${{pair.key}}: ${{pair.value}}
